// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file GoalInfoSubscriber.h
 * This header file contains the declaration of the subscriber functions.
 *
 * This file was generated by the tool fastcdrgen.
 */


#ifndef _ACTION_MSGS_MSG_GOALINFO_SUBSCRIBER_H_
#define _ACTION_MSGS_MSG_GOALINFO_SUBSCRIBER_H_

#include <functional>

#include <fastrtps/fastrtps_fwd.h>
#include <fastrtps/subscriber/SubscriberListener.h>
#include <fastrtps/subscriber/SampleInfo.h>
#include "GoalInfoPubSubTypes.h"

class GoalInfoSubscriber
{
public:
	GoalInfoSubscriber(eprosima::fastrtps::Participant *participant = nullptr);
	virtual ~GoalInfoSubscriber();
	void set_callback(std::function<void(const action_msgs::msg::GoalInfo&)> cb);
	bool init();
	void run();
private:
	eprosima::fastrtps::Participant *mp_participant;
	eprosima::fastrtps::Subscriber *mp_subscriber;
	static std::function<void(const action_msgs::msg::GoalInfo&)> callback;
	
	bool should_delete_participant = false;

	class SubListener : public eprosima::fastrtps::SubscriberListener
	{
	public:
		SubListener() : n_matched(0),n_msg(0){};
		~SubListener(){};
		void onSubscriptionMatched(eprosima::fastrtps::Subscriber* sub,eprosima::fastrtps::rtps::MatchingInfo& info);
		void onNewDataMessage(eprosima::fastrtps::Subscriber* sub);
		eprosima::fastrtps::SampleInfo_t m_info;
		int n_matched;
		int n_msg;
	} m_listener;
	action_msgs::msg::GoalInfoPubSubType myType;
};

#endif // _ACTION_MSGS_MSG_GoalInfo_SUBSCRIBER_H_